// config.example.js
// RENOMEIE ESTE ARQUIVO PARA config.js E PREENCHA COM SUAS teste de up no githubCHAVES DO SUPABASE

const SUPABASE_CONFIG = {
    URL: 'SUA_URL_DO_SUPABASE_AQUI',
    ANON_KEY: 'SUA_CHAVE_ANON_DO_SUPABASE_AQUI',
    ADMIN_EMAIL: 'SEU_EMAIL_DE_ADMIN_AQUI'
};